name: Krafty Cuts
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75057
title: 'Hair salon in a truck!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bebbb6'
    - '#63605b'
    - '#141412'
    - '#dddcda'
    - '#87847f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
